version: '3.8'

services:
  mysqldb:
    container_name: mysqldb-container
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  server-api:
    container_name: server-api-container
    depends_on:
      - mysqldb
    build:
      context: ./server-api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - ./server-api:/usr/src/app
    environment:
      - DB_HOST=mysqldb-container
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  server-ui:
    container_name: server-ui-container
    depends_on:
      - server-api
    build:
      context: ./server-ui
      dockerfile: Dockerfile
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    volumes:
      - ./server-api:/usr/src/app
    networks:
      - frontend


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server-api
      - server-ui
    volumes:
      - /home/ubuntu/Project-PressTI/pressti.conf:/etc/nginx/pressti.conf:rw
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
    networks:
      - backend
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
